const prisma = require("../lib/prisma");
const bcrypt = require("bcryptjs");

async function main() {
  console.log("🌱 Seeding MCC Shop database...");

  // --- Admin user ---
  const adminPassword = await bcrypt.hash("admin123", 10);
  await prisma.user.upsert({
    where: { phone: "0200000001" },
    update: {},
    create: {
      name: "MCC Admin",
      phone: "0200000001",
      email: "admin@mccshop.com",
      password: adminPassword,
      role: "ADMIN",
    },
  });

  // --- Test customer ---
  const customerPassword = await bcrypt.hash("customer123", 10);
  await prisma.user.upsert({
    where: { phone: "0200000002" },
    update: {},
    create: {
      name: "Test Customer",
      phone: "0200000002",
      email: "client@test.com",
      password: customerPassword,
      role: "CUSTOMER",
    },
  });

  // --- Test rider ---
  const riderPassword = await bcrypt.hash("rider123", 10);
  const riderUser = await prisma.user.upsert({
    where: { phone: "0200000003" },
    update: {},
    create: {
      name: "Test Rider",
      phone: "0200000003",
      email: "rider@test.com",
      password: riderPassword,
      role: "RIDER",
    },
  });
  await prisma.rider.upsert({
    where: { userId: riderUser.id },
    update: {},
    create: { userId: riderUser.id },
  });

  // --- Products from MCC MVP Catalogue ---
  const products = [
    {
      skuCode: "PNT-001",
      name: "Emulsion Paint",
      category: "Paints",
      unitSize: "5 Gallon",
      costPrice: 650,
      sellingPrice: 780,
      bulkThreshold: 5,
      bulkPrice: 750,
      stockQty: 30,
      lowStockAlert: 5,
      dispatchMode: "VAN",
      images: "/emulsion_paint.png",
      isPublished: false,
      mvpPriority: false,
    },
    {
      skuCode: "PNT-002",
      name: "Gloss Paint",
      category: "Paints",
      unitSize: "1 Gallon",
      costPrice: 180,
      sellingPrice: 220,
      bulkThreshold: 10,
      bulkPrice: 210,
      stockQty: 50,
      lowStockAlert: 10,
      dispatchMode: "BIKE",
      images: "/oil_paint.png",
      isPublished: false,
      mvpPriority: false,
    },
    {
      skuCode: "ADH-001",
      name: "Silicone Sealant",
      category: "Adhesives",
      unitSize: "Tube",
      costPrice: 28,
      sellingPrice: 38,
      bulkThreshold: 20,
      bulkPrice: 35,
      stockQty: 100,
      lowStockAlert: 20,
      dispatchMode: "BIKE",
      images: "/silicon_sealant.png",
      isPublished: false,
      mvpPriority: false,
    },
    {
      skuCode: "SAF-001",
      name: "Safety Helmet",
      category: "Safety",
      unitSize: "Unit",
      costPrice: 55,
      sellingPrice: 75,
      bulkThreshold: 10,
      bulkPrice: 70,
      stockQty: 40,
      lowStockAlert: 8,
      dispatchMode: "BIKE",
      images: "/helmet.png",
      isPublished: false,
      mvpPriority: false,
    },
    {
      skuCode: "TLS-001",
      name: "Trowel",
      category: "Tools",
      unitSize: "Unit",
      costPrice: 25,
      sellingPrice: 40,
      bulkThreshold: 20,
      bulkPrice: 36,
      stockQty: 60,
      lowStockAlert: 10,
      dispatchMode: "BIKE",
      images: "/trowel.png",
      isPublished: false,
      mvpPriority: false,
    },
    {
      skuCode: "ELE-001",
      name: "LED Bulb",
      category: "Electrical",
      unitSize: "12W",
      costPrice: 18,
      sellingPrice: 28,
      bulkThreshold: 50,
      bulkPrice: 25,
      stockQty: 200,
      lowStockAlert: 30,
      dispatchMode: "BIKE",
      images: "/led_bulb.png",
      isPublished: false,
      mvpPriority: false,
    },
    {
      skuCode: "PLM-001",
      name: "Faucet",
      category: "Plumbing",
      unitSize: "Unit",
      costPrice: 120,
      sellingPrice: 160,
      bulkThreshold: 5,
      bulkPrice: 150,
      stockQty: 25,
      lowStockAlert: 5,
      dispatchMode: "BIKE",
      images: "/faucet.png",
      isPublished: false,
      mvpPriority: false,
    },
    {
      skuCode: "HDR-001",
      name: "Door Lock",
      category: "Hardware",
      unitSize: "Unit",
      costPrice: 140,
      sellingPrice: 190,
      bulkThreshold: 5,
      bulkPrice: 180,
      stockQty: 30,
      lowStockAlert: 5,
      dispatchMode: "BIKE",
      images: "/locks.png",
      isPublished: false,
      mvpPriority: false,
    },
    {
      skuCode: "OFF-001",
      name: "Home Chair",
      category: "Office",
      unitSize: "Unit",
      costPrice: 650,
      sellingPrice: 820,
      bulkThreshold: 2,
      bulkPrice: 790,
      stockQty: 15,
      lowStockAlert: 3,
      dispatchMode: "VAN",
      images: "/office_chairs.jpeg",
      isPublished: false,
      mvpPriority: false,
    },
    {
      skuCode: "PAN-001",
      name: "PVC Ceiling Panel",
      category: "Panels",
      unitSize: "Length",
      costPrice: 85,
      sellingPrice: 115,
      bulkThreshold: 50,
      bulkPrice: 108,
      stockQty: 500,
      lowStockAlert: 50,
      dispatchMode: "PICKUP",
      images: "/ceiling_panel.jpeg",
      isPublished: false,
      mvpPriority: false,
    },
    // --- Standard Emulsion Paint (single product, 5 colour options) ---
    {
      skuCode: "PNT-EMU-001",
      name: "MCC Standard Emulsion Paint",
      brand: "MCC",
      category: "Paints",
      subCategory: "Emulsion Paint",
      unitSize: "20 Litres",
      costPrice: 240,
      sellingPrice: 300,
      bulkThreshold: 5,
      bulkPrice: 280,
      stockQty: 250,
      lowStockAlert: 10,
      dispatchMode: "VAN",
      isFragile: false,
      isHazardous: false,
      images: "/mcc_emulsion_paint.jpeg",
      notes: "colours:White,Magnolia,Ivory,Grey,Broken White",
      isPublished: true,
      mvpPriority: true,
    },
    // Unpublish old individual colour SKUs
    { skuCode: "PNT-EMU-WHITE",  name: "MCC White Emulsion Paint",        brand:"MCC", category:"Paints", subCategory:"Emulsion Paint", unitSize:"20 Litres", costPrice:240, sellingPrice:300, bulkThreshold:5, bulkPrice:280, stockQty:50, lowStockAlert:10, dispatchMode:"VAN", images:"/mcc_emulsion_paint.jpeg", isPublished:false, mvpPriority:false },
    { skuCode: "PNT-EMU-MAGNOLIA",name: "MCC Magnolia Emulsion Paint",    brand:"MCC", category:"Paints", subCategory:"Emulsion Paint", unitSize:"20 Litres", costPrice:240, sellingPrice:300, bulkThreshold:5, bulkPrice:280, stockQty:50, lowStockAlert:10, dispatchMode:"VAN", images:"/mcc_emulsion_paint.jpeg", isPublished:false, mvpPriority:false },
    { skuCode: "PNT-EMU-IVORY",  name: "MCC Ivory Emulsion Paint",        brand:"MCC", category:"Paints", subCategory:"Emulsion Paint", unitSize:"20 Litres", costPrice:240, sellingPrice:300, bulkThreshold:5, bulkPrice:280, stockQty:50, lowStockAlert:10, dispatchMode:"VAN", images:"/mcc_emulsion_paint.jpeg", isPublished:false, mvpPriority:false },
    { skuCode: "PNT-EMU-GREY",   name: "MCC Grey Emulsion Paint",         brand:"MCC", category:"Paints", subCategory:"Emulsion Paint", unitSize:"20 Litres", costPrice:240, sellingPrice:300, bulkThreshold:5, bulkPrice:280, stockQty:50, lowStockAlert:10, dispatchMode:"VAN", images:"/mcc_emulsion_paint.jpeg", isPublished:false, mvpPriority:false },
    { skuCode: "PNT-EMU-BWHITE", name: "MCC Broken White Emulsion Paint", brand:"MCC", category:"Paints", subCategory:"Emulsion Paint", unitSize:"20 Litres", costPrice:240, sellingPrice:300, bulkThreshold:5, bulkPrice:280, stockQty:50, lowStockAlert:10, dispatchMode:"VAN", images:"/mcc_emulsion_paint.jpeg", isPublished:false, mvpPriority:false },
    // --- Acrylic Premium Emulsion Paint (single product, 5 colour options) ---
    {
      skuCode: "PNT-ACR-001",
      name: "MCC Acrylic Premium Emulsion Paint",
      brand: "MCC",
      category: "Paints",
      subCategory: "Acrylic Emulsion",
      unitSize: "20 Litres",
      costPrice: 520,
      sellingPrice: 650,
      bulkThreshold: 3,
      bulkPrice: 620,
      stockQty: 150,
      lowStockAlert: 5,
      dispatchMode: "VAN",
      isFragile: false,
      isHazardous: false,
      images: "/acrylic_paint.jpg",
      notes: "colours:White,Magnolia,Ivory,Grey,Broken White",
      isPublished: true,
      mvpPriority: true,
    },
    // Unpublish old individual colour SKUs
    { skuCode: "PNT-ACR-WHITE",  name: "MCC White Acrylic Premium Emulsion Paint",        brand:"MCC", category:"Paints", subCategory:"Acrylic Emulsion", unitSize:"20 Litres", costPrice:520, sellingPrice:650, bulkThreshold:3, bulkPrice:620, stockQty:30, lowStockAlert:5, dispatchMode:"VAN", images:"/mcc_emulsion_paint.jpeg", isPublished:false, mvpPriority:false },
    { skuCode: "PNT-ACR-MAGNOLIA",name: "MCC Magnolia Acrylic Premium Emulsion Paint",   brand:"MCC", category:"Paints", subCategory:"Acrylic Emulsion", unitSize:"20 Litres", costPrice:520, sellingPrice:650, bulkThreshold:3, bulkPrice:620, stockQty:30, lowStockAlert:5, dispatchMode:"VAN", images:"/mcc_emulsion_paint.jpeg", isPublished:false, mvpPriority:false },
    { skuCode: "PNT-ACR-IVORY",  name: "MCC Ivory Acrylic Premium Emulsion Paint",        brand:"MCC", category:"Paints", subCategory:"Acrylic Emulsion", unitSize:"20 Litres", costPrice:520, sellingPrice:650, bulkThreshold:3, bulkPrice:620, stockQty:30, lowStockAlert:5, dispatchMode:"VAN", images:"/mcc_emulsion_paint.jpeg", isPublished:false, mvpPriority:false },
    { skuCode: "PNT-ACR-GREY",   name: "MCC Grey Acrylic Premium Emulsion Paint",         brand:"MCC", category:"Paints", subCategory:"Acrylic Emulsion", unitSize:"20 Litres", costPrice:520, sellingPrice:650, bulkThreshold:3, bulkPrice:620, stockQty:30, lowStockAlert:5, dispatchMode:"VAN", images:"/mcc_emulsion_paint.jpeg", isPublished:false, mvpPriority:false },
    { skuCode: "PNT-ACR-BWHITE", name: "MCC Broken White Acrylic Premium Emulsion Paint", brand:"MCC", category:"Paints", subCategory:"Acrylic Emulsion", unitSize:"20 Litres", costPrice:520, sellingPrice:650, bulkThreshold:3, bulkPrice:620, stockQty:30, lowStockAlert:5, dispatchMode:"VAN", images:"/mcc_emulsion_paint.jpeg", isPublished:false, mvpPriority:false },
    // --- Oil Paint (single product, 3 colour options) ---
    {
      skuCode: "PNT-OIL-001",
      name: "Oil Paint",
      category: "Paints",
      subCategory: "Oil Paint",
      unitSize: "4 Litres",
      costPrice: 160,
      sellingPrice: 200,
      bulkThreshold: 10,
      bulkPrice: 185,
      stockQty: 120,
      lowStockAlert: 8,
      dispatchMode: "BIKE",
      images: "/oil_paint.png",
      notes: "colours:White,Dark Brown,Dark Grey",
      isPublished: true,
      mvpPriority: true,
    },
    // Unpublish old individual colour SKUs
    { skuCode: "PNT-OIL-WHITE",   name: "Oil Paint – White",     category:"Paints", subCategory:"Oil Paint", unitSize:"4 Litres", costPrice:160, sellingPrice:200, bulkThreshold:10, bulkPrice:185, stockQty:40, lowStockAlert:8, dispatchMode:"BIKE", images:"/oil_paint.png", isPublished:false, mvpPriority:false },
    { skuCode: "PNT-OIL-DKBROWN", name: "Oil Paint – Dark Brown", category:"Paints", subCategory:"Oil Paint", unitSize:"4 Litres", costPrice:160, sellingPrice:200, bulkThreshold:10, bulkPrice:185, stockQty:40, lowStockAlert:8, dispatchMode:"BIKE", images:"/oil_paint.png", isPublished:false, mvpPriority:false },
    { skuCode: "PNT-OIL-DKGREY",  name: "Oil Paint – Dark Grey",  category:"Paints", subCategory:"Oil Paint", unitSize:"4 Litres", costPrice:160, sellingPrice:200, bulkThreshold:10, bulkPrice:185, stockQty:40, lowStockAlert:8, dispatchMode:"BIKE", images:"/oil_paint.png", isPublished:false, mvpPriority:false },
    // --- Thinner ---
    {
      skuCode: "PNT-THIN-001",
      name: "Paint Thinner",
      category: "Paints",
      subCategory: "Accessories",
      unitSize: "4 Litres",
      costPrice: 120,
      sellingPrice: 150,
      bulkThreshold: 10,
      bulkPrice: 135,
      stockQty: 60,
      lowStockAlert: 10,
      dispatchMode: "BIKE",
      images: "/paint_thinner.jpg",
      isPublished: true,
      mvpPriority: false,
    },
    // --- Plasterboards ---
    {
      skuCode: "PLB-9MM-001",
      name: "Plasterboard 9mm",
      category: "Boards",
      unitSize: "Sheet",
      costPrice: 120,
      sellingPrice: 150,
      bulkThreshold: 20,
      bulkPrice: 135,
      stockQty: 200,
      lowStockAlert: 20,
      dispatchMode: "VAN",
      images: "/plasterboard_9mm.jpg",
      isPublished: true,
      mvpPriority: true,
    },
    {
      skuCode: "PLB-12MM-001",
      name: "Plasterboard 12mm",
      category: "Boards",
      unitSize: "Sheet",
      costPrice: 160,
      sellingPrice: 200,
      bulkThreshold: 20,
      bulkPrice: 180,
      stockQty: 200,
      lowStockAlert: 20,
      dispatchMode: "VAN",
      images: "/plasterboard_12mm.jpg",
      isPublished: true,
      mvpPriority: true,
    },
    // --- Joint Products ---
    {
      skuCode: "JNT-CMP-001",
      name: "Joint Compound",
      category: "Boards",
      subCategory: "Jointing",
      unitSize: "20 Litres",
      costPrice: 280,
      sellingPrice: 350,
      bulkThreshold: 5,
      bulkPrice: 320,
      stockQty: 80,
      lowStockAlert: 10,
      dispatchMode: "VAN",
      images: "/joint_compound.jpg",
      isPublished: true,
      mvpPriority: true,
    },
    {
      skuCode: "JNT-PWD-001",
      name: "Joint Powder",
      category: "Boards",
      subCategory: "Jointing",
      unitSize: "25kg Bag",
      costPrice: 280,
      sellingPrice: 350,
      bulkThreshold: 5,
      bulkPrice: 320,
      stockQty: 80,
      lowStockAlert: 10,
      dispatchMode: "VAN",
      images: "/skimming_powder.jpg",
      isPublished: true,
      mvpPriority: true,
    },
    // --- PVC Panels & Boards ---
    {
      skuCode: "PVC-PNL-001",
      name: "PVC Ceiling Panels",
      category: "Panels",
      unitSize: "Per Piece",
      costPrice: 48,
      sellingPrice: 60,
      bulkThreshold: 50,
      bulkPrice: 55,
      stockQty: 1000,
      lowStockAlert: 50,
      dispatchMode: "VAN",
      images: "/ceiling_panel.jpeg",
      notes: "colours:White,Brown",
      isPublished: true,
      mvpPriority: true,
    },
    { skuCode: "PVC-WH-001", name: "PVC Ceiling Panels – White", category:"Panels", unitSize:"Per Piece", costPrice:48, sellingPrice:60, bulkThreshold:50, bulkPrice:55, stockQty:500, lowStockAlert:50, dispatchMode:"VAN", images:"/ceiling_panel.jpeg", isPublished:false, mvpPriority:false },
    { skuCode: "PVC-BR-001", name: "PVC Ceiling Panels – Brown", category:"Panels", unitSize:"Per Piece", costPrice:48, sellingPrice:60, bulkThreshold:50, bulkPrice:55, stockQty:500, lowStockAlert:50, dispatchMode:"VAN", images:"/ceiling_panel.jpeg", isPublished:false, mvpPriority:false },
    {
      skuCode: "PVC-BD-001",
      name: "PVC Ceiling Boards",
      category: "Panels",
      unitSize: "Per Sheet",
      costPrice: 32,
      sellingPrice: 40,
      bulkThreshold: 50,
      bulkPrice: 36,
      stockQty: 500,
      lowStockAlert: 50,
      dispatchMode: "VAN",
      images: "/pvc_ceiling_board.jpg",
      isPublished: true,
      mvpPriority: false,
    },
    // --- Wall Cladding ---
    {
      skuCode: "WCL-001",
      name: "Wall Cladding",
      category: "Panels",
      unitSize: "Per m²",
      costPrice: 120,
      sellingPrice: 150,
      bulkThreshold: 20,
      bulkPrice: 135,
      stockQty: 200,
      lowStockAlert: 20,
      dispatchMode: "VAN",
      images: "/wall_cladding.jpg",
      isPublished: true,
      mvpPriority: false,
    },

    // =============================================
    // FURNITURE – SOFAS
    // =============================================
    {
      skuCode: "SFA-FAB-3S",
      name: "3-Seater Fabric Sofa",
      category: "Furniture",
      subCategory: "Sofas",
      unitSize: "Unit",
      costPrice: 2000,
      sellingPrice: 2500,
      bulkThreshold: 2,
      bulkPrice: 2400,
      stockQty: 10,
      lowStockAlert: 2,
      dispatchMode: "VAN",
      images: "/gechi_blazer.jpg",
      isPublished: true,
      mvpPriority: true,
    },
    {
      skuCode: "SFA-FAB-LS",
      name: "L-Shaped Fabric Sofa",
      category: "Furniture",
      subCategory: "Sofas",
      unitSize: "Unit",
      costPrice: 3700,
      sellingPrice: 4600,
      bulkThreshold: 2,
      bulkPrice: 4400,
      stockQty: 8,
      lowStockAlert: 2,
      dispatchMode: "VAN",
      images: "/gechi_lux_sofa.jpg",
      isPublished: true,
      mvpPriority: true,
    },
    {
      skuCode: "SFA-LEA-LS",
      name: "L-Shaped Half Leather Sofa",
      category: "Furniture",
      subCategory: "Sofas",
      unitSize: "Unit",
      costPrice: 5600,
      sellingPrice: 7000,
      bulkThreshold: 2,
      bulkPrice: 6700,
      stockQty: 6,
      lowStockAlert: 1,
      dispatchMode: "VAN",
      images: "/showroom_ck810w.jpeg",
      isPublished: true,
      mvpPriority: true,
    },
    {
      skuCode: "SFA-LEA-LUX",
      name: "Full Leather Luxury Sofa",
      category: "Furniture",
      subCategory: "Sofas",
      unitSize: "Unit",
      costPrice: 12000,
      sellingPrice: 15000,
      bulkThreshold: 2,
      bulkPrice: 14500,
      stockQty: 4,
      lowStockAlert: 1,
      dispatchMode: "VAN",
      images: "/gechi_lawrence_str.jpg",
      isPublished: true,
      mvpPriority: true,
    },

    // =============================================
    // FURNITURE – BEDS & MATTRESSES
    // =============================================
    {
      skuCode: "BED-UPH-QN",
      name: "Queen Size Upholstered Bed",
      category: "Furniture",
      subCategory: "Beds",
      unitSize: "Unit",
      costPrice: 1600,
      sellingPrice: 2000,
      bulkThreshold: 2,
      bulkPrice: 1900,
      stockQty: 8,
      lowStockAlert: 2,
      dispatchMode: "VAN",
      images: "/showroom_1825b_bed.jpeg",
      isPublished: true,
      mvpPriority: true,
    },
    {
      skuCode: "MAT-QN-001",
      name: "Queen Size Mattress",
      category: "Furniture",
      subCategory: "Mattresses",
      unitSize: "Unit",
      costPrice: 1120,
      sellingPrice: 1400,
      bulkThreshold: 2,
      bulkPrice: 1350,
      stockQty: 15,
      lowStockAlert: 3,
      dispatchMode: "VAN",
      images: "/showroom_mattress_balance.jpeg",
      isPublished: true,
      mvpPriority: true,
    },
    {
      skuCode: "BED-UPH-KG",
      name: "King Size Upholstered Bed",
      category: "Furniture",
      subCategory: "Beds",
      unitSize: "Unit",
      costPrice: 3200,
      sellingPrice: 4000,
      bulkThreshold: 2,
      bulkPrice: 3800,
      stockQty: 6,
      lowStockAlert: 1,
      dispatchMode: "VAN",
      images: "/showroom_ck820w.jpeg",
      isPublished: true,
      mvpPriority: true,
    },
    {
      skuCode: "MAT-KG-001",
      name: "King Size Mattress",
      category: "Furniture",
      subCategory: "Mattresses",
      unitSize: "Unit",
      costPrice: 1600,
      sellingPrice: 2000,
      bulkThreshold: 2,
      bulkPrice: 1900,
      stockQty: 10,
      lowStockAlert: 2,
      dispatchMode: "VAN",
      images: "/showroom_mattress_gravity.jpeg",
      isPublished: true,
      mvpPriority: true,
    },

    // =============================================
    // FURNITURE – DINING TABLES
    // =============================================
    {
      skuCode: "DIN-4ST-001",
      name: "4-Seater Dining Set",
      category: "Furniture",
      subCategory: "Dining",
      unitSize: "Set",
      costPrice: 3600,
      sellingPrice: 4500,
      bulkThreshold: 2,
      bulkPrice: 4300,
      stockQty: 8,
      lowStockAlert: 2,
      dispatchMode: "VAN",
      images: "/gechi_lawrence_cor.jpg",
      isPublished: true,
      mvpPriority: true,
    },
    {
      skuCode: "DIN-6ST-001",
      name: "6-Seater Dining Set",
      category: "Furniture",
      subCategory: "Dining",
      unitSize: "Set",
      costPrice: 4800,
      sellingPrice: 6000,
      bulkThreshold: 2,
      bulkPrice: 5700,
      stockQty: 6,
      lowStockAlert: 1,
      dispatchMode: "VAN",
      images: "/gechi_nico_table.jpg",
      isPublished: true,
      mvpPriority: true,
    },
    {
      skuCode: "DIN-LUX-001",
      name: "Marble / Ceramic Luxury Dining Set",
      category: "Furniture",
      subCategory: "Dining",
      unitSize: "Set",
      costPrice: 6400,
      sellingPrice: 8000,
      bulkThreshold: 2,
      bulkPrice: 7600,
      stockQty: 4,
      lowStockAlert: 1,
      dispatchMode: "VAN",
      images: "/showroom_vs18_table.jpeg",
      isPublished: true,
      mvpPriority: true,
    },
  ];

  for (const product of products) {
    await prisma.product.upsert({
      where: { skuCode: product.skuCode },
      update: product,
      create: product,
    });
  }

  await prisma.coupon.upsert({
    where: { code: "WELCOME10" },
    update: {},
    create: {
      code: "WELCOME10",
      description: "10% off your first order",
      discountType: "PERCENT",
      discountValue: 10,
      minOrderValue: 100,
      active: true,
    },
  });
  await prisma.coupon.upsert({
    where: { code: "SAVE50" },
    update: {},
    create: {
      code: "SAVE50",
      description: "GHS 50 off orders above GHS 500",
      discountType: "FIXED",
      discountValue: 50,
      minOrderValue: 500,
      active: true,
    },
  });

  console.log("✅ Database seeded successfully!");
}

main()
  .catch((e) => {
    console.error("❌ Seed error: ", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
